[2024-05-15T10:48:19.986+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T10:48:20.005+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: parsing_recipes.parse_recipes scheduled__2024-05-15T10:44:00+00:00 [queued]>
[2024-05-15T10:48:20.009+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: parsing_recipes.parse_recipes scheduled__2024-05-15T10:44:00+00:00 [queued]>
[2024-05-15T10:48:20.010+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-15T10:48:20.017+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): parse_recipes> on 2024-05-15 10:44:00+00:00
[2024-05-15T10:48:20.021+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'parsing_recipes', 'parse_recipes', 'scheduled__2024-05-15T10:44:00+00:00', '--job-id', '5954', '--raw', '--subdir', 'DAGS_FOLDER/recipes.py', '--cfg-path', '/tmp/tmp3sc6cmp7']
[2024-05-15T10:48:20.023+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=213) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-05-15T10:48:20.024+0000] {standard_task_runner.py:91} INFO - Job 5954: Subtask parse_recipes
[2024-05-15T10:48:20.024+0000] {standard_task_runner.py:63} INFO - Started process 215 to run task
[2024-05-15T10:48:20.062+0000] {task_command.py:426} INFO - Running <TaskInstance: parsing_recipes.parse_recipes scheduled__2024-05-15T10:44:00+00:00 [running]> on host d0ca377f4b6d
[2024-05-15T10:48:20.105+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='parsing_recipes' AIRFLOW_CTX_TASK_ID='parse_recipes' AIRFLOW_CTX_EXECUTION_DATE='2024-05-15T10:44:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-15T10:44:00+00:00'
[2024-05-15T10:48:20.106+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T10:48:20.114+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T10:48:20.115+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/recipes.py", line 31, in parse_recipes
    with open(path + 'latest_salad_recipes.txt', encoding='utf8') as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Development/airflow_scraping/dags/latest_salad_recipes.txt'
[2024-05-15T10:48:20.121+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=parsing_recipes, task_id=parse_recipes, run_id=scheduled__2024-05-15T10:44:00+00:00, execution_date=20240515T104400, start_date=20240515T104820, end_date=20240515T104820
[2024-05-15T10:48:20.128+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5954 for task parse_recipes ([Errno 2] No such file or directory: '/Development/airflow_scraping/dags/latest_salad_recipes.txt'; 215)
[2024-05-15T10:48:20.163+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-15T10:48:20.175+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-15T10:48:20.177+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
